services:
  - type: web
    name: linklive
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: -XX:MaxRAMPercentage=75 -XX:+UseSerialGC
